name: kafka-cohort

networks:
  kafka-cohort-network:
    driver: bridge

services:
  app:
    image: mcr.microsoft.com/devcontainers/python:3.11
    volumes:
      - .:/workspaces/kafka-tutorial
    command: sleep infinity

  # Kafka Broker 1
  kafka-broker-1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-1
    ports:
      - "9092:9092" # External communication
      - "9093:9093" # For external clients
    environment:
      # Basic Kafka configuration
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:29093,2@kafka-broker-2:29093

      # Listeners configuration
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-1:29094,CONTROLLER://kafka-broker-1:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:29094,EXTERNAL://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Storage configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/data

      # Debug and cluster settings
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.server.KafkaConfig=INFO,state.change.logger=INFO"
      CLUSTER_ID: xZYp0ABC123DEF456GHI
    volumes:
      - ./data/kafka-broker-1:/var/lib/kafka/data
    networks:
      - kafka-cohort-network

  # Kafka Broker 2 (new)
  kafka-broker-2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker-2
    ports:
      - "9094:9094" # External communication
      - "9095:9095" # For external clients
    environment:
      # Basic Kafka configuration
      KAFKA_BROKER_ID: 2
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker-1:29093,2@kafka-broker-2:29093

      # Listeners configuration
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-2:29094,CONTROLLER://kafka-broker-2:29093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:29094,EXTERNAL://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Storage configuration
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/data

      # Debug and cluster settings
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.server.KafkaConfig=INFO,state.change.logger=INFO"
      CLUSTER_ID: xZYp0ABC123DEF456GHI
    volumes:
      - ./data/kafka-broker-2:/var/lib/kafka/data
    networks:
      - kafka-cohort-network

  # Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker-1:29094,PLAINTEXT://kafka-broker-2:29094
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    networks:
      - kafka-cohort-network

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka-broker-1:29094,PLAINTEXT://kafka-broker-2:29094
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
    networks:
      - kafka-cohort-network
